export const fruits = [
  { id: 'n72WkC', name: 'Lychee', value: 'lychee' },
  { id: 'TzT1Tg', name: 'Pineapple', value: 'pineapple' },
  { id: 'M6UgBf', name: 'Mango', value: 'mango' },
  { id: 'RX2fby', name: 'Guava', value: 'guava' },
  { id: 'R8uGZP', name: 'Starfruit', value: 'starfruit' },
  { id: 'wA0N73', name: 'Papaya', value: 'papaya' },
  { id: 'U6ydnH', name: 'Dragon Fruit', value: 'dragon fruit' },
  { id: 'e9yzIk', name: 'Watermelon', value: 'watermelon' },
  { id: '3q4qjK', name: 'Banana', value: 'banana' },
  { id: 'iAK7hm', name: 'Jackfruit', value: 'jackfruit' },
  { id: 'SXx1xV', name: 'Passion Fruit', value: 'passion fruit' },
  { id: 'UHdFr1', name: 'Kumquat', value: 'kumquat' },
  { id: 'm9z9mK', name: 'Longan', value: 'longan' },
  { id: '4Nmu3c', name: 'Pomelo', value: 'pomelo' },
  { id: 'Q2PxoH', name: 'Custard Apple', value: 'custard apple' },
  { id: 'sLDtVz', name: 'Kiwi', value: 'kiwi' },
  { id: 'HyRt6j', name: 'Avocado', value: 'avocado' },
  { id: 'xQlW9k', name: 'Pomegranate', value: 'pomegranate' },
  { id: 'eU7V5d', name: 'Grapefruit', value: 'grapefruit' },
  { id: 'rJ6F5h', name: 'Cantaloupe', value: 'cantaloupe' },
  { id: 'zN3K2a', name: 'Plum', value: 'plum' },
];
